In [1]:
#Code with the topic : Ridge vs Lasso

#Objective:

#Compare Ridge and Lasso regression models using the same dataset
#and evaluate their performance with MSE and R².

#Techologies:

#pandas
#Python
#Visual Studio Code
#Jupyter Notebook

#Method used:

#Lasso
#Ridge

In [2]:
#We import the libraries

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge,Lasso
from sklearn.metrics import mean_squared_error, r2_score

In [3]:
#Load the dataset

data = pd.read_csv("Ridge_vs_Lasso.csv")

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   area    6 non-null      int64
 1   rooms   6 non-null      int64
 2   age     6 non-null      int64
 3   price   6 non-null      int64
dtypes: int64(4)
memory usage: 324.0 bytes

In [5]:
data.head()

   area  rooms  age    price
0   120      3    5   250000
1   150      4   10   320000
2    90      2   15  1800000
3   200      5    3   450000
4   170      4    8   360000

In [6]:
data.describe()

             area     rooms        age         price
count    6.000000  6.000000   6.000000  6.000000e+00
mean   140.000000  3.500000   8.833333  5.666667e+05
std     40.987803  1.048809   4.445972  6.097103e+05
min     90.000000  2.000000   3.000000  2.200000e+05
25%    112.500000  3.000000   5.750000  2.675000e+05
50%    135.000000  3.500000   9.000000  3.400000e+05
75%    165.000000  4.000000  11.500000  4.275000e+05
max    200.000000  5.000000  15.000000  1.800000e+06

In [7]:
data.columns

Index(['area', 'rooms', 'age', 'price'], dtype='object')

In [8]:
#X and Y

X = data.drop("price", axis = 1)
Y = data["price"]

In [9]:
#split training and testing data

x_train,x_test,y_train,y_test = train_test_split(X,Y, test_size=0.2, random_state=42)

In [10]:
#Feature scales

scaler = StandardScaler()


x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [11]:
#Ridge Model

ridge = Ridge(alpha=1.0)
ridge.fit(x_train_scaled, y_train)

y_pred_ridge = ridge.predict(x_test_scaled)

print("Ridge")
print("MSE",mean_squared_error(y_test, y_pred_ridge))
print("R2", r2_score(y_test, y_pred_ridge))

Ridge
MSE 168625815156.91003
R2 -136.65372665870206

In [12]:
#Lasso Model

lasso = Lasso(alpha=0.1)
lasso.fit(x_train_scaled, y_train)

y_pred_lasso = lasso.predict(x_test_scaled)

In [ ]:
print("\n=== Lasso ===")
print("MSE:", mean_squared_error(y_test, y_pred_lasso))
print("R²:", r2_score(y_test, y_pred_lasso))

# Coefficients
print("\nRidge coefficients:")
print(ridge.coef_)

print("\nLasso coefficients:")
print(lasso.coef_)

=== Lasso ===
MSE: 15025935807994.535
R²: -12265.070047342479

Coeficientes Ridge:
[ -25026.80827046 -268750.33555476   77096.71837137]

Coeficientes Lasso:
[ 1112450.15411647 -4678416.03779903 -3167983.13146236]